apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudback-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crudback
  template:
    metadata:
      labels:
        app: crudback
    spec:
      containers:
      - name: crudback
        image: snezhana02/crudback
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "secret"
        - name: DB_NAME
          value: "db2"
